export const STUDY_TYPE_META = {
  PRODUCT_VALIDATION: {
    label: "消费品验证",
    desc: "比较新品的购买概率、目标人群、价格弹性与竞品替代。",
    icon: "📦",
    color: "#4f8cff",
  },
  PRICING_STUDY: {
    label: "消费品定价",
    desc: "比较不同价格对选择概率、相对收入和利润的影响。",
    icon: "฿",
    color: "#78a7ff",
  },
  VENUE_STUDY: {
    label: "线下门店验证",
    desc: "评估餐厅、咖啡馆、酒吧和零售门店的到店意向、客群与经营约束。",
    icon: "🏪",
    color: "#62c6ff",
  },
  SITE_COMPARISON: {
    label: "商圈与选址比较",
    desc: "对比候选点位的目标客群覆盖、出行阻力、竞争强度与相对排序。",
    icon: "📍",
    color: "#9b8cff",
  },
  CREATIVE_TEST: {
    label: "广告与素材测试",
    desc: "比较广告图片、文案、视频脚本或落地页的理解、信任与行动倾向。",
    icon: "🎯",
    color: "#ff8ab3",
  },
  OPERATING_SCENARIO: {
    label: "门店经营情景",
    desc: "比较营业时间、容量、活动、客单价和服务配置对结果的影响。",
    icon: "🧭",
    color: "#5dd8c1",
  },
} as const;

export const PLAN_META = {
  PREVIEW: {
    label: "预览版",
    population: 100,
    mc_rounds: 40,
    scenarios: 2,
    competitors: 1,
    credits: 0,
    price_thb: 0,
    availability: "self_service",
    desc: "每个账号 1 次，用于检查输入和方向，不作为正式决策依据。",
  },
  STANDARD: {
    label: "标准版",
    population: 10_000,
    mc_rounds: 80,
    scenarios: 3,
    competitors: 3,
    credits: 5,
    price_thb: 0,
    availability: "self_service",
    desc: "适合初筛一个产品与基础价格方案。",
  },
  PROFESSIONAL: {
    label: "专业版",
    population: 30_000,
    mc_rounds: 150,
    scenarios: 5,
    competitors: 5,
    credits: 20,
    price_thb: 7_900,
    availability: "self_service",
    desc: "完整竞品选择集、价格弹性、细分和情景分析。",
  },
} as const;

export const TEMPLATES = [
  {
    id: "tpl_pet_water",
    key: "pet_water",
    label: "泰国宠物智能饮水机",
    study_type: "PRODUCT_VALIDATION",
    category: "PET_WATER_FOUNTAIN",
    icon: "🐈",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "立即查看",
    result_href: "/demo/pet-water",
  },
  {
    id: "tpl_new_product",
    key: "new_product",
    label: "通用消费新品",
    study_type: "PRODUCT_VALIDATION",
    category: "GENERIC_CONSUMER_PRODUCT",
    icon: "📦",
    recommended_plan: "STANDARD",
    scenarios: 3,
    est_time: "约 5–15 分钟",
  },
  {
    id: "tpl_pricing",
    key: "pricing",
    label: "消费品价格测试",
    study_type: "PRICING_STUDY",
    category: "GENERIC_CONSUMER_PRODUCT",
    icon: "฿",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 10–20 分钟",
  },
  {
    id: "tpl_restaurant",
    key: "restaurant",
    label: "清迈餐厅开店验证",
    study_type: "VENUE_STUDY",
    category: "RESTAURANT",
    icon: "🍜",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 15–30 分钟",
  },
  {
    id: "tpl_cafe",
    key: "cafe",
    label: "Nimman 咖啡馆",
    study_type: "VENUE_STUDY",
    category: "CAFE",
    icon: "☕",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 15–30 分钟",
  },
  {
    id: "tpl_bar",
    key: "bar",
    label: "旅游区酒吧",
    study_type: "VENUE_STUDY",
    category: "BAR",
    icon: "🍸",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 15–30 分钟",
  },
  {
    id: "tpl_site",
    key: "site",
    label: "候选商圈 / 点位比较",
    study_type: "SITE_COMPARISON",
    category: "RETAIL",
    icon: "📍",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 15–30 分钟",
  },
  {
    id: "tpl_creative",
    key: "creative",
    label: "广告图片与文案测试",
    study_type: "CREATIVE_TEST",
    category: "GENERIC_CONSUMER_PRODUCT",
    icon: "🎯",
    recommended_plan: "STANDARD",
    scenarios: 3,
    est_time: "约 10–20 分钟",
  },
  {
    id: "tpl_retail",
    key: "retail",
    label: "社区零售门店",
    study_type: "VENUE_STUDY",
    category: "RETAIL",
    icon: "🛍️",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 15–30 分钟",
  },
  {
    id: "tpl_operations",
    key: "operations",
    label: "营业时间与容量优化",
    study_type: "OPERATING_SCENARIO",
    category: "RESTAURANT",
    icon: "🧭",
    recommended_plan: "PROFESSIONAL",
    scenarios: 5,
    est_time: "约 15–30 分钟",
  },
] as const;
