"""Build compact Malaysia ADM0/ADM1 assets from pinned geoBoundaries data."""

from __future__ import annotations

import json
from pathlib import Path

import build_thailand_boundaries as geometry


ROOT = Path(__file__).resolve().parents[1]
BASE = (
    "https://github.com/wmgeolab/geoBoundaries/raw/9469f09/"
    "releaseData/gbOpen/MYS"
)
ADM0_URL = f"{BASE}/ADM0/geoBoundaries-MYS-ADM0_simplified.geojson"
ADM1_URL = f"{BASE}/ADM1/geoBoundaries-MYS-ADM1_simplified.geojson"
BOUNDS = (99.5, 0.5, 119.5, 7.6)


def main() -> None:
    geometry.BOUNDS = BOUNDS
    geometry.VIEWBOX = (640.0, 300.0)
    adm0 = geometry.fetch_json(ADM0_URL)
    adm1 = geometry.fetch_json(ADM1_URL)

    country_rings = []
    for raw_ring in geometry.exterior_rings(adm0["features"][0]["geometry"]):
        ring = geometry.simplify_ring(raw_ring, 0.018)
        if ring and abs(geometry.signed_area(ring)) >= 0.001:
            country_rings.append(ring)

    states = []
    state_paths = []
    for feature in adm1["features"]:
        rings = []
        for raw_ring in geometry.exterior_rings(feature["geometry"]):
            ring = geometry.simplify_ring(raw_ring, 0.012)
            if ring and abs(geometry.signed_area(ring)) >= 0.0005:
                rings.append(ring)
        if not rings:
            continue
        primary = max(rings, key=lambda item: abs(geometry.signed_area(item)))
        longitudes = [point[0] for point in primary]
        latitudes = [point[1] for point in primary]
        states.append(
            {
                "name": feature["properties"]["shapeName"],
                "iso": feature["properties"].get("shapeISO"),
                "centroid": geometry.centroid(primary),
                "bbox": [
                    round(min(longitudes), 4),
                    round(min(latitudes), 4),
                    round(max(longitudes), 4),
                    round(max(latitudes), 4),
                ],
                "rings": rings,
            }
        )
        state_paths.append(geometry.path_for_rings(rings))

    catalog = {
        "version": "MY-GEOBOUNDARIES-ADM1-2026.08.1",
        "boundary_year": "2019",
        "source": "geoBoundaries gbOpen MYS ADM0/ADM1",
        "source_url": "https://www.geoboundaries.org/api/current/gbOpen/MYS/ADM1/",
        "source_data": "OpenStreetMap, Wambacher",
        "license": "Open Data Commons Open Database License 1.0",
        "bounds": list(BOUNDS),
        "country_rings": country_rings,
        "provinces": sorted(states, key=lambda item: item["name"]),
    }
    catalog_path = ROOT / "data_catalog" / "geo" / "malaysia_adm1_boundaries_v1.json"
    catalog_path.write_text(
        json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )

    typescript = (
        "// Generated by scripts/build_malaysia_boundaries.py from "
        "geoBoundaries gbOpen MYS ADM0/ADM1.\n"
        f"export const MALAYSIA_BOUNDARY_VERSION = {json.dumps(catalog['version'])};\n"
        f"export const MALAYSIA_BOUNDARY_SOURCE = {json.dumps(catalog['source'])};\n"
        f"export const MALAYSIA_MAP_BOUNDS = {json.dumps(list(BOUNDS))} as const;\n"
        f"export const MALAYSIA_COUNTRY_PATH = {json.dumps(geometry.path_for_rings(country_rings))};\n"
        f"export const MALAYSIA_STATE_PATH = {json.dumps(''.join(state_paths))};\n"
    )
    frontend_path = ROOT / "apps" / "web" / "lib" / "malaysia-boundary.ts"
    frontend_path.write_text(typescript, encoding="utf-8")
    print(f"Wrote {len(states)} states, {len(country_rings)} country rings.")


if __name__ == "__main__":
    main()
