"""Versioned technical inputs for population-balancing experiments."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from typing import Any, Mapping

import numpy as np
import pandas as pd


CONTROL_DIMENSIONS = ("region", "gender", "income_tier")


def _control_name(dimension: str, value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_")
    return f"{dimension}__{safe}"


def _canonical_records(
    frame: pd.DataFrame,
    columns: list[str],
) -> list[dict[str, Any]]:
    return json.loads(
        frame[columns].to_json(
            orient="records",
            double_precision=15,
        )
    )


@dataclass(frozen=True)
class PopulationSynthesisInputs:
    seed_population: pd.DataFrame
    incidence: pd.DataFrame
    controls: pd.Series
    manifest: Mapping[str, Any]


def build_population_synthesis_inputs(
    seed_population: pd.DataFrame,
    calibration_profile: Mapping[str, Any],
    represented_population: int,
    seed: int,
) -> PopulationSynthesisInputs:
    if represented_population <= 0:
        raise ValueError("represented_population must be positive")
    required = set(CONTROL_DIMENSIONS)
    missing = required - set(seed_population.columns)
    if missing:
        raise ValueError(
            f"Population seed is missing controls: {sorted(missing)}"
        )
    population_profile = calibration_profile["population"]
    incidence = pd.DataFrame(
        {"total_persons": np.ones(len(seed_population), dtype=float)}
    )
    control_values: dict[str, float] = {
        "total_persons": float(represented_population)
    }
    variable_mapping: dict[str, dict[str, str]] = {}
    for dimension in CONTROL_DIMENSIONS:
        targets = population_profile[dimension]
        variable_mapping[dimension] = {}
        for value, share in targets.items():
            name = _control_name(dimension, str(value))
            incidence[name] = (
                seed_population[dimension].astype(str) == str(value)
            ).astype(float)
            control_values[name] = float(share) * represented_population
            variable_mapping[dimension][str(value)] = name

    seed_columns = [
        "person_id",
        *CONTROL_DIMENSIONS,
        "age_group",
        "province",
        "household_size",
    ]
    records = _canonical_records(seed_population, seed_columns)
    seed_bytes = json.dumps(
        records,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    controls_bytes = json.dumps(
        control_values,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    manifest = {
        "schema_version": "population-input-manifest-v1",
        "dataset_id": (
            f"synthetic_seed_{hashlib.sha256(seed_bytes).hexdigest()[:16]}"
        ),
        "source_profile_version": calibration_profile.get("version"),
        "source_profile_status": calibration_profile.get("status"),
        "seed_sample_status": "synthetic_seed_not_observed_microdata",
        "geographic_scope": "Thailand national and province assignment",
        "seed": int(seed),
        "seed_rows": len(seed_population),
        "represented_population": int(represented_population),
        "seed_sha256": hashlib.sha256(seed_bytes).hexdigest(),
        "controls_sha256": hashlib.sha256(controls_bytes).hexdigest(),
        "variable_mapping_version": "population-controls-v1",
        "variable_mapping": variable_mapping,
        "missing_values": {
            column: int(seed_population[column].isna().sum())
            for column in seed_columns
        },
        "permission": (
            "Technical synthetic seed generated by CMAI from versioned "
            "official aggregate margins and disclosed engineering priors."
        ),
        "sources": list(calibration_profile.get("sources") or []),
        "source_acquired_at": sorted(
            {
                str(source["fetched_at"])
                for source in calibration_profile.get("sources") or []
                if source.get("fetched_at")
            }
        ),
        "source_urls": sorted(
            {
                str(source[url_key])
                for source in calibration_profile.get("sources") or []
                for url_key in ("dataset_page", "api_url")
                if source.get(url_key)
            }
        ),
        "limitations": [
            "The seed is synthetic and is not Thai household microdata.",
            "Controls calibrate decision-unit margins, not household-person relationships.",
            "Joint distributions remain dependent on the synthetic seed assumptions.",
        ],
    }
    manifest_bytes = json.dumps(
        manifest,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    manifest["manifest_sha256"] = hashlib.sha256(
        manifest_bytes
    ).hexdigest()
    return PopulationSynthesisInputs(
        seed_population=seed_population,
        incidence=incidence,
        controls=pd.Series(control_values, dtype=float),
        manifest=manifest,
    )


def control_comparison(
    incidence: pd.DataFrame,
    weights: np.ndarray,
    controls: pd.Series,
) -> pd.DataFrame:
    generated = incidence.mul(weights, axis=0).sum(axis=0)
    comparison = pd.DataFrame(
        {
            "control": controls.index,
            "target": controls.to_numpy(dtype=float),
            "generated": generated.loc[controls.index].to_numpy(dtype=float),
        }
    )
    comparison["absolute_error"] = (
        comparison["generated"] - comparison["target"]
    ).abs()
    comparison["absolute_percentage_point_error"] = np.where(
        comparison["control"] == "total_persons",
        comparison["absolute_error"]
        / comparison["target"].clip(lower=1.0)
        * 100.0,
        comparison["absolute_error"]
        / float(controls["total_persons"])
        * 100.0,
    )
    return comparison
